spring:
  flyway:
    enabled: false
    url: jdbc:mysql://10.15.99.217:3306/one-service-oauth2-testlocal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    user: one-service-oauth2-testlocal
    password: one@2019

  application:
    name: oauth2

  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.15.99.217:3306/one-service-oauth2-testlocal?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: one-service-oauth2-testlocal
    password: one@2019
    maximum-pool-size: 20
    minimum-idle: 6
    connection-timeout: 30000
    idle-timeout: 60000
    max-lifetime: 1800000
    leak-detection-threshold: 200000
  hikari:
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: xxxx
            client-secret: xxxx
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email
              - profile
      provider:
        google:
          issuer-uri: https://accounts.google.com
server:
  port: 9000
  servlet:
    context-path: /api
batch:
  active: true
async:
  thread-pool:
    core-thread: 5
    max-thread: 10
    queue-capacity: 100
auth:
  login:
    max-failed: 3
    lock-minutes: 15
security:
  jwt:
    # KEY tối thiểu 32 bytes cho HS256
    secret: Ak3hbR0drmcbSoIMyVdldA6jCbWxRbE_Iy17Rlpl2XAa
    access-token-seconds: 36000  # 10h (ta sẽ trả expires_in = 35999)
    refresh-token-seconds: 2592000 # 30 ngày
    issuer: jwt-auth-service
app:
  frontend:
    success-url: "http://localhost:3000/auth/callback"